---

- name: PARSE SHOW COMMANDS ON DIFFERNET PLATFORMS WITH pyATS / GENIE
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    _command: "show version"

  tasks:

  - name: pyATS parser
    block:
    - name: parse command
      ansible.netcommon.cli_parse:
        command: "{{ _command }}"
        parser:
          name: ansible.netcommon.pyats
      register: _parser_result
    - name: print parser output
      debug:
        var: _parser_result.parsed
