---

- name: "DIFFERENT IOS CONFIG EXAMPLES"
  hosts: ios
  gather_facts: no
  connection: network_cli
  vars_files:
    - "{{ playbook_dir }}/vars/ios-config.yml"
  become: yes
  tasks: 

  - name: TOP LEVEL
    block:
      - name: top level config
        ios_config:
          lines: "{{ top_level_lines }}"
          match: line
        register: _result_toplevel
      - debug: 
          var: _result_toplevel
    tags: toplevel
  
  - name: "TOP LEVEL EXACT MATCHING: {{ top_level_exact_include }}"
    block:
      - name: get running config 
        ios_command:
          commands: "show running-config | include {{ top_level_exact_include }}"
        register: _show_runn
      - name: top level exact matching
        ios_config:
          running_config: "{{ _show_runn.stdout[0] }}"
          lines: "{{ top_level_exact_lines }}"
          match: exact
          before: "{{ top_level_exact_before }}"
        register: _result_toplevel_exact
      - debug: 
          var: _result_toplevel_exact
    tags: toplevelexact

  - name: "NESTED INTERFACE {{ nested_intf_name }}"
    block:
      - name: nested config
        ios_config: 
          lines: "{{ nested_intf_lines }}"
          parents: "interface {{ nested_intf_name }}" 
          match: line
        register: _result_nested
      - debug: 
          var: _result_nested
    tags: nested

  - name: "NESTED INTERFACE {{ nested_intf_name }} EXACT MATCHING"
    block:
      - name: nested config exact match
        ios_config: 
          lines: "{{ nested_intf_lines }}"
          parents: "interface {{ nested_intf_name }}" 
          match: exact
          before: "default interface {{ nested_intf_name }}"
        register: _result_nested
      - debug: 
          var: _result_nested
    tags: nestedexact

  - name: MULTI NESTED QoS CONFIG
    block:
      - name: "QoS class map {{ qos_classmap_name }}"
        ios_config:
          lines: "{{ qos_classmap_lines }}"
          parents: "class-map match-all {{ qos_classmap_name }}"
      - name: "QoS configure policer in {{ qos_classmap_name }} class"
        ios_config:
          lines: "{{ qos_policer_lines }}"
          parents: "{{ qos_policer_parents }}"
        register: _result_multinested
      - debug: 
            var: _result_multinested
    tags: multinested
        