---

top_level_lines: 
  - hostname {{ inventory_hostname }}

top_level_exact_include: ip http
top_level_exact_lines:
  - ip http server
  - ip http port 3023
  - ip http authentication local
  - no ip http secure-server

nested_intf_name: Loopback2
nested_intf_lines: 
    - description ANSIBLE CONFIGURED
    - ip address 10.199.199.1 255.255.255.255

qos_policy_map: Foo
qos_classmap_lines:
  - match dscp cs7
qos_classmap_name: Scavenger
qos_cir: "64000"
qos_policer_lines: 
  - conform-action transmit
  - exceed-action drop
qos_policer_parents:
  - "policy-map {{ qos_policy_map }}"
  - "class {{ qos_classmap_name }}"
  - "police cir {{ qos_cir }}"